### ISSUE TITLE
OSRM Nodejs 5xx error

### ISSUE THREAD

**Issue by venkatavendra** [door2door-io/osrm-express-server-demo#10]
Hey, I got  5XX errors from load balancer metrics show that these are 502 errors and looking at our internal logs it says that the connection was reset by the peer(which is nothing but the target in this case) while trying to read response headers for the request sent. And these error logs coincide with the time when there are 502 errors.

This kind of error messages are seen if the HTTP keep-alive duration on the targets is less than the ALB idle timeout (60 seconds in this case). So, increasing the keepalive duration on the Application level should work?

2020/05/27 14:42:40.322 POST request /car/table from client 34.xxx.xxx.xxx sent to target 172.xx.xxx.xxx:32768.. the target closed the connection with a RST while waiting for response headers
2020/05/27 15:34:56.001 POST request /car/table from client 34.xxx.xxx.xxx sent to target 172.xx.xxx.xxx:32768.. the target closed the connection with a RST while waiting for response headers
2020/05/27 15:53:06.685 POST request /car/table from client 34.xxx.xxx.xxx sent to target 172.xx.xxx.xxx:32768.. the target closed the connection with a RST while waiting for response headers

Will the below code snippet solve our problem?

server.keepAliveTimeout = 61 * 1000;
server.headersTimeout = 65 * 1000;

**Comment by quiqua** [comment]
This repository is just showcasing how to use OSRM as a library within a Node.js application.

> Will the below code snippet solve our problem?
>
> server.keepAliveTimeout = 61 * 1000;
> server.headersTimeout = 65 * 1000;

We can't answer your question regarding the interaction with the load-balancer and the Node.js application, but you can try this yourself.

Please note that OSRM currently only supports Node.js until version 10.
