### ISSUE TITLE
OSRM v5.24.0 support

### ISSUE THREAD

**Issue by TimMcCauley** [door2door-io/osrm-express-server-demo#12]
Greetings @quiqua is there a chance this repo will support the latest OSRM 5.24.0? Currently I am seeing

```
/usr/src/app/src/lib/osrm.js:9
  return new OSRM(opts);
         ^

TypeError: File is incompatible with this version of OSRM: /data/osrm/uk/britain-and-ireland-latest.osrm.icd prepared with OSRM 5.24.0 but this is v5.22.0 (at include/storage/tar.hpp:204)
```

I'm happy to raise a PR if you could guide me a little.

**Comment by TimMcCauley** [comment]
Will have to be taken care in osrm backend repository

**Comment by quiqua** [comment]
I have not yet build a newer version of OSRM and ran it with this version.

The README of this project is currently a bit off as it assumed different version of OSRM, e.g. this line:
```
docker pull osrm/osrm-backend:v5.22.0
```
and this one:

```
# extract the network and create the osrm file(s)
docker run -it -v $(pwd)/data:/data osrm/osrm-backend:v5.16.1 osrm-extract -p /opt/car.lua /data/osrm/example-areas/example-areas.osm.pbf
```
should use the same version number.

Yet as long as there exists no docker container provided by OSRM directly for version 5.23, there is nothing I can do really.

The only advice I can give you is to use the same version of OSRM to preprocess the data and then run the routing engine.

**Comment by TimMcCauley** [comment]
Thank you @quiqua makes sense. Works perfectly fine with 5.23.0 now, too - https://www.npmjs.com/package/osrm
