### ISSUE TITLE
Dockerfile.osmium-tool won't build properly

### ISSUE THREAD

**Issue by jmarca** [door2door-io/osrm-express-server-demo#2]
I'm wondering if you are interested in bug reports etc on this, or whether it is just an example project.  Anyway, I ran into an issue building osmium with your Dockerfile.  

Specifically, libprotozero is no longer included in libosmium (see <https://github.com/osmcode/libosmium#prerequisites>)

The fix is pretty easy, just pull it from https://github.com/mapbox/protozero and build it.

I ran into a few more issues as well, and can probably send a decent pull request, but only if you're maintaining this.

**Comment by quiqua** [comment]
Oh sorry for the late response.
Yeah I've encountered the issue as well and will push a fix soon.

**Comment by quiqua** [comment]
Thanks for pointing this out @jmarca.
