### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by pango89** [door2door-io/osrm-express-server-demo#5]
Hi,
I am running my own OSRM express server which have data for 6 USA states.
I am trying to use the Table API and I am able to run it successfully when I give it around ~1000 coordinates  and fetching a matrix of 1000x1000 entries.
However, when I am increasing the data to ~2000 coordinates, it fails giving the error that the Payload is too large. 
Is there a way to query such large payloads also?
My use case may need a table query of upto ~20000 coordinates.

My API call : http://192.168.5.193:5000/table
Payload: 
[Payload.txt](https://github.com/door2door-io/osrm-express-server-demo/files/1889975/Payload.txt)
Response:
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>PayloadTooLargeError: request entity too large
            <br> &nbsp; &nbsp;at readStream (/usr/src/app/node_modules/raw-body/index.js:155:17)
            <br> &nbsp; &nbsp;at getRawBody (/usr/src/app/node_modules/raw-body/index.js:108:12)
            <br> &nbsp; &nbsp;at read (/usr/src/app/node_modules/body-parser/lib/read.js:77:3)
            <br> &nbsp; &nbsp;at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:134:5)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
            <br> &nbsp; &nbsp;at /usr/src/app/node_modules/express/lib/router/index.js:284:7
            <br> &nbsp; &nbsp;at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
            <br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at internalNext (/usr/src/app/node_modules/helmet/index.js:45:33)
        </pre>
    </body>
</html>

**Comment by quiqua** [comment]
Hey!

Could you try this SO answer: https://stackoverflow.com/a/36514330

You need to set this here: 
https://github.com/door2door-io/osrm-express-server-demo/blob/df4d681734d66fc9cb4ce63319793a79f867ee99/app/src/app.js#L15-L16

Add the specific `limit: Xmb` options and rebuild the docker image.

**Comment by quiqua** [comment]
The default limit defined by `body-parser` is `100kb`: 
https://github.com/expressjs/body-parser/blob/0632e2f378d53579b6b2e4402258f4406e62ac6f/lib/types/json.js#L53-L55

Hope this helps :)

**Comment by pango89** [comment]
Thanks a lot for your reply.
I was able to figure out the same solution.
Thanks 👍

**Comment by saddam0710** [comment]
> The default limit defined by `body-parser` is `100kb`:
> https://github.com/expressjs/body-parser/blob/0632e2f378d53579b6b2e4402258f4406e62ac6f/lib/types/json.js#L53-L55
> 
> Hope this helps :)

You save my time
Thanks 👍

**Comment by telcotronics** [comment]
I don't use body-parser. use express. how can I solve that
