### ISSUE TITLE
Are the osrm datafiles loaded into the memory?

### ISSUE THREAD

**Issue by rajat23495** [door2door-io/osrm-express-server-demo#9]
I have a doubt if the osrm datafiles are loaded into the RAM at start time or does it read from the disk?
Because processing time is high and so is the response time for this.
I am doing it for the planet dataset using aws EFS as mount storage. distance matrix calls are taking quite long.

**Comment by quiqua** [comment]
OSRM usually loads all the files into memory: https://github.com/Project-OSRM/osrm-backend/wiki/Disk-and-Memory-Requirements

I don't know if there is an option when running it as a node library to access the `--mmap` setting as described here: https://github.com/Project-OSRM/osrm-backend/issues/5543#issuecomment-529462298

I'll close this issue as it is related to OSRM directly and not at the example project here.
